// <auto-generated />
namespace Bluejay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Companies_relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Companies_relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201705142357113_add_Companies_relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
